//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterWeb.Logic.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMonsterService")]
    public interface IMonsterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetGender", ReplyAction="http://tempuri.org/IMonsterService/GetGenderResponse")]
        Monster.App.DataAcess.Models.GenderDAO[] GetGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetGender", ReplyAction="http://tempuri.org/IMonsterService/GetGenderResponse")]
        System.Threading.Tasks.Task<Monster.App.DataAcess.Models.GenderDAO[]> GetGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetMonsterTypes", ReplyAction="http://tempuri.org/IMonsterService/GetMonsterTypesResponse")]
        Monster.App.DataAcess.Models.MonsterTypeDAO[] GetMonsterTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetMonsterTypes", ReplyAction="http://tempuri.org/IMonsterService/GetMonsterTypesResponse")]
        System.Threading.Tasks.Task<Monster.App.DataAcess.Models.MonsterTypeDAO[]> GetMonsterTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetTitles", ReplyAction="http://tempuri.org/IMonsterService/GetTitlesResponse")]
        Monster.App.DataAcess.Models.TitleDAO[] GetTitles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/GetTitles", ReplyAction="http://tempuri.org/IMonsterService/GetTitlesResponse")]
        System.Threading.Tasks.Task<Monster.App.DataAcess.Models.TitleDAO[]> GetTitlesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonsterServiceChannel : MonsterWeb.Logic.ServiceReference1.IMonsterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonsterServiceClient : System.ServiceModel.ClientBase<MonsterWeb.Logic.ServiceReference1.IMonsterService>, MonsterWeb.Logic.ServiceReference1.IMonsterService {
        
        public MonsterServiceClient() {
        }
        
        public MonsterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonsterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonsterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonsterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Monster.App.DataAcess.Models.GenderDAO[] GetGender() {
            return base.Channel.GetGender();
        }
        
        public System.Threading.Tasks.Task<Monster.App.DataAcess.Models.GenderDAO[]> GetGenderAsync() {
            return base.Channel.GetGenderAsync();
        }
        
        public Monster.App.DataAcess.Models.MonsterTypeDAO[] GetMonsterTypes() {
            return base.Channel.GetMonsterTypes();
        }
        
        public System.Threading.Tasks.Task<Monster.App.DataAcess.Models.MonsterTypeDAO[]> GetMonsterTypesAsync() {
            return base.Channel.GetMonsterTypesAsync();
        }
        
        public Monster.App.DataAcess.Models.TitleDAO[] GetTitles() {
            return base.Channel.GetTitles();
        }
        
        public System.Threading.Tasks.Task<Monster.App.DataAcess.Models.TitleDAO[]> GetTitlesAsync() {
            return base.Channel.GetTitlesAsync();
        }
    }
}
